[HACK] Update rxtx to 2.2, adding 64-bit Linux support.
(This is a hack since these files should never live in the Wiring
repository; they're external dependencies and should be resolved and
downloaded in the usual way. They're also definitely NOT "shared"
build resources, as there's a per-OS shared library along with the
JAR, which obviously don't belong under build/shared!)

The 2.1-based version of the RXTX serial library is crashing on 64-bit
Linux with the same problems mentioned here:

    http://forums.gentoo.org/viewtopic-p-6032253.html

Follow same workaround recommended in the forum thread by upgrading to
the 2.2pre2 binaries, obtained from here:

    http://rxtx.qbang.org/pub/rxtx/rxtx-2.2pre2-bins.zip

For reference (and probably eventual GPL compliance), the sources are
available here:

    http://rxtx.qbang.org/pub/rxtx/rxtx-2.2pre2.zip

Keep both 32- and 64-bit librxtxSerial.so versions around under
build/shared/lib/serial/, in subdirectories linux-i686 and
linux-x86_64. This lets the wiring shell script on Linux put the right
one into LD_LIBRARY_PATH using uname -m.

This change also lets us check whether we're missing the correct
shared object file for the machine hardware we're running on, enabling
us to exit with a sensible error message instead of crashing with
UnsatisfiedLinkError.

There's a warning about a JAR/JNI version mismatch; I'm assuming this
is spurious, as the library binaries were obtained directly from the
official rxtx development webpage.

Signed-off-by: Marti Bolivar <mbolivar@leaflabs.com>

diff --git a/build/linux/dist/wiring b/build/linux/dist/wiring
--- a/build/linux/dist/wiring
+++ b/build/linux/dist/wiring
@@ -102,8 +102,14 @@ export PATH="$JDKDIR/bin":"$PATH"
 log PATH
 
 # Hack up LD_LIBRARY_PATH so JNI finds librxtxSerial.so
-BUNDLED_LIBS="$APPDIR/lib/"
-export LD_LIBRARY_PATH="$BUNDLED_LIBS/serial/":"$LD_LIBRARY_PATH"
+BUNDLED_LIBS="$APPDIR/lib"
+SERIAL_LIB_DIR="$BUNDLED_LIBS/serial/linux-"`uname -m`
+if [ ! -d $SERIAL_LIB_DIR ]; then
+    echo "Missing rxtx support; cannot start Wiring IDE" 2>&1
+    exit 1
+fi
+log SERIAL_LIB_DIR
+export LD_LIBRARY_PATH="$SERIAL_LIB_DIR":"$LD_LIBRARY_PATH"
 log LD_LIBRARY_PATH
 
 # Start Processing in the same directory as this script
